name: "Deploy Hugo to S3 and Cloudfront using OIDC"
description: "Build and deploy Hugo static websites to AWS S3 and Cloudfront using OIDC"
author: "oharkins"
branding:
  icon: package
  color: yellow
inputs:
  hugo-version:
    description: "Choose a valid Hugo version"
    required: true
  target:
    description: "A deployment target"
    required: false
    default: ""
  config:
    description: "Config file"
    required: false
    default: ""
  environment:
    description: "environment"
    required: false
    default: ""
  skip-deployment:
    description: "Skip deployment to AWS"
    required: false
    default: "false"
  pipeline-execution-role:
    description: The role that will be assumed during the Configure AWS step.
    required: true
    type: string
  aws-region:
    description: AWS Region the stack is being deployed to
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - id: install-hugo
      run: |
        HUGO_DOWNLOAD=hugo_extended_${{ inputs.hugo-version }}_Linux-64bit.tar.gz
        wget https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/${HUGO_DOWNLOAD}
        tar xvzf ${HUGO_DOWNLOAD} hugo
        mv hugo $HOME/hugo
      shell: bash

    - id: download-themes
      run: |
        git submodule init
        git submodule update
      shell: bash

    - id: hugo-build
      run: $HOME/hugo
      shell: bash

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.pipeline-execution-role }}
        role-duration-seconds: 3600
        role-skip-session-tagging: true

    - id: deploy-to-s3
      if: inputs.skip-deployment == 'false'
      run: |
        HUGO_FLAGS=" --logLevel info --invalidateCDN --maxDeletes -1"

        if [[ "${{ inputs.environment }}" ]]; then
          HUGO_FLAGS="$HUGO_FLAGS --environment=${{ inputs.environment }}"
        fi

        if [[ "${{ inputs.config }}" ]]; then
          HUGO_FLAGS="$HUGO_FLAGS --config=${{ inputs.config }}"
        fi

        if [[ "${{ inputs.target }}" ]]; then
          HUGO_FLAGS="$HUGO_FLAGS --target=${{ inputs.target }}"
        fi

        $HOME/hugo deploy $HUGO_FLAGS
      shell: bash